name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  packages: write

jobs:
  ci:
    uses: Vempain/vempain-workflows/.github/workflows/frontend-library.yaml@main
    secrets: inherit
